spring:

  config:
    import: optional:file:.env[.properties]

  cache:
    type: redis
    cache-names: redis-cache

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  datasource:
    url: jdbc:postgresql://${HOST}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:liquibase/db.changelog-master.xml
    enabled: true

security:
  jwt:
    secret: ${JWT_SECRET}
    access: 3600000
    refresh: 2592000000

minio:
  bucket: ${MINIO_BUCKET}
  url: ${MINIO_URL}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}
